#!/bin/bash

dmk_image=scratch
dmk_makecmd=make

if [ -f .dmkrc ]; then
    . .dmkrc
fi

DMKUID=$(id -u)
DMKGID=$(id -g)

docker run -v "$(pwd):/build" -u root -it "$dmk_image" \
/bin/bash -c " \
addgroup --gid $DMKGID tmpgrp && \
adduser --disabled-password --gecos '' -u $DMKUID --gid $DMKGID $USER && \
cd /build && sudo -u $USER $dmk_makecmd $*"

dlast=$(docker ps -l -q)
docker stop $dlast &>/dev/null
docker rm $dlast &>/dev/null
