#!/bin/bash

dmk_host=unix:///var/run/docker.sock
dmk_image=scratch
dmk_buildvol="$(pwd)"
dmk_voldriver=local
dmk_makecmd=make

if [ -f .dmkrc ]; then
    . .dmkrc
fi

DMKUID=$(id -u)
DMKGID=$(id -g)

docker -H "$dmk_host" run -v "$dmk_buildvol:/build" "--volume-driver=$dmk_voldriver" -u root -it "$dmk_image" \
/bin/bash -c " \
addgroup --gid $DMKGID tmpgrp && \
adduser --disabled-password --gecos '' -u $DMKUID --gid $DMKGID $USER && \
chown -R $USER:tmpgrp /root && \
cd /build && sudo -u $USER $dmk_makecmd $*"

dlast=$(docker -H "$dmk_host" ps -l -q)
docker -H "$dmk_host" stop $dlast &>/dev/null
docker -H "$dmk_host" rm $dlast &>/dev/null
